/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#727783",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#424752",
        "on-secondary-fixed": "#002022",
        "secondary-fixed": "#7df4ff",
        "primary": "#00478d",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface-dim": "#d9dadb",
        "on-primary-container": "#c8daff",
        "secondary": "#006970",
        "surface-container-low": "#f3f4f5",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#141d23",
        "tertiary-fixed-dim": "#bfc8d0",
        "surface-bright": "#f8f9fa",
        "primary-fixed": "#d6e3ff",
        "error": "#ba1a1a",
        "surface-container": "#edeeef",
        "tertiary-fixed": "#dbe4ed",
        "on-secondary-container": "#006e75",
        "surface": "#f8f9fa",
        "on-background": "#191c1d",
        "on-tertiary-container": "#d1dae4",
        "primary-fixed-dim": "#a9c7ff",
        "surface-variant": "#e1e3e4",
        "surface-container-high": "#e7e8e9",
        "background": "#f8f9fa",
        "surface-tint": "#005db6",
        "secondary-container": "#7af1fc",
        "surface-container-highest": "#e1e3e4",
        "on-secondary-fixed-variant": "#004f54",
        "on-tertiary-fixed-variant": "#3f484f",
        "on-primary-fixed-variant": "#00468c",
        "tertiary-container": "#576068",
        "primary-container": "#005eb8",
        "secondary-fixed-dim": "#5dd8e2",
        "outline-variant": "#c2c6d4",
        "tertiary": "#404850",
        "inverse-primary": "#a9c7ff",
        "on-surface": "#191c1d",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "inverse-surface": "#2e3132",
        "on-primary-fixed": "#001b3d",
        "inverse-on-surface": "#f0f1f2"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1440px",
        "gutter": "24px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
